name: Dev-Events CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Sample-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3
      - name: SSH TO EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
        run: |
          echo "$PRIVATE_KEY"
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "private_key"
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY root@ec2-13-201-78-176.ap-south-1.compute.amazonaws.com'
          # Your deployment commands go here
          pwd
          ls
          npm install
          npm run dev
