name: Dev-Events CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Sample-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3
      - name: SSH TO EC2
        env:
          PRIVATE_KEY: $${{ secrets.SSH_PRIVATE_KEY }}
        run: |
           echo "$PRIVATE_KEY"
           echo "private_key"
           ls
