name: Dev-Events CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Sample-Checking:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3

      - name: SSH TO EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-235-2-173.ap-south-1.compute.amazonaws.com "
            # Now we have got the access of EC2 and we will start the deploy .
            ls
            whoami
            export NVM_DIR=\"\$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
            nvm use 20
            git clone https://github.com/Nevin505/DevEvents.git DevEvents
            cd /home/ubuntu/DevEvents &&
            git fetch --all &&
            git pull origin master &&
            npm install &&
           pm2 restart DevEvents || pm2 start npm --name DevEvents -- run dev
            "
